#!/usr/bin/bash

PROJECT_NAME=mktdump
BUILD_VERBOSE=OFF
source $TOOLCHAIN_PATH/build.in

if [[ $1 == "command" ]]; then
    echo "mktdump specific command"

else
     echo "ERROR: unknown command"
fi
